/*
 * Generated by: Office Vitae Mongoose Schema Designer
 * At: 17 december 2019
 * Author: Marc de Hoogh
 */

const mongoose=require('mongoose');
// Comment out the following lines if you're not using the integer data types provided by the mongoose-long and mongoose-int32 libraries.
require('mongoose-long')(mongoose);
var Int32=require('mongoose-int32');

const userSchema=mongoose.Schema({
                                  name:{type:mongoose.Schema.Types.String,unique:true,minlength:1},
                                  password:{type:mongoose.Schema.Types.String,minlength:1},
                                 });
module.exports=userSchema;
