/*
 * Generated by: Office Vitae Mongoose Schema Designer
 * At: 16 december 2019
 * Author: Marc de Hoogh
 */

const mongoose=require('mongoose');
// Comment out the following lines if you're not using the integer data types provided by the mongoose-long and mongoose-int32 libraries.
require('mongoose-long')(mongoose);
var Int32=require('mongoose-int32');

const cookSchema=mongoose.Schema({
                                  name:{type:mongoose.Schema.Types.String,unique:true},
                                  image:mongoose.Schema.Types.String,
                                 });
module.exports=cookSchema;
