/*
 * Generated by: Office Vitae Mongoose Schema Designer
 * At: 16 december 2019
 * Author: Marc de Hoogh
 */
module.exports=(router,conn)=>{
	const cooks=require('../controllers/msd.cook.controller.js')(conn);
	router.post('/cooks',cooks.create);
	router.get('/cooks',cooks.findAll);
	router.get('/cooks/:cookId',cooks.findOne);
	router.put('/cooks/:cookId',cooks.update);
	router.delete('/cooks/:cookId',cooks.delete);
}
