/*
 * Generated by: Office Vitae Mongoose Schema Designer
 * At: 16 december 2019
 * Author: Marc P. de Hoogh
 */
module.exports=(router,conn)=>{
	const recipes=require('../controllers/msd.recipe.controller.js')(conn);
	router.post('/recipes',recipes.create);
	router.get('/recipes',recipes.findAll);
	router.get('/recipes/:recipeId',recipes.findOne);
	router.put('/recipes/:recipeId',recipes.update);
	router.delete('/recipes/:recipeId',recipes.delete);
}

