/*
 * Generated by: Office Vitae Mongoose Schema Designer
 * At: 16 december 2019
 * Author: Marc de Hoogh
 */

const mongoose=require('mongoose');
const cookSchema=require('../schemas/msd.cook.schema.js');

module.exports=(conn)=>{
  return(conn?conn:mongoose).model('cook',cookSchema);
}
