/*
 * Generated by: Office Vitae Mongoose Schema Designer
 * At: 17 december 2019
 * Author: Marc P. de Hoogh
 */

const mongoose=require('mongoose');
const userSchema=require('../schemas/msd.user.schema.js');

module.exports=(conn)=>{
  return(conn?conn:mongoose).model('user',userSchema);
}
