/*
 * Generated by: Office Vitae Mongoose Schema Designer
 * At: 16 december 2019
 * Author: Marc P. de Hoogh
 */

const mongoose=require('mongoose');
const recipeSchema=require('../schemas/msd.recipe.schema.js');

module.exports=(conn)=>{
  return(conn?conn:mongoose).model('recipe',recipeSchema);
}
